packages:
  - name: jira-github
    environment:
      GITHUB_CLASSIC_TOKEN: '${GITHUB_CLASSIC_TOKEN}'
      #LOG_DESTINATIONS: '[{"papertrail":{"token":"${PAPERTRAIL_TOKEN}"}}]'
    actions:
      - name: webhook 
        runtime: nodejs:default  
        limits:
          timeout: 15000
          memory: 256